### ISSUE TITLE
cf-console on Windows? (or Cygwin)

### ISSUE THREAD

**Issue by hagemt** [danhigham/cf-console#4]
During CF training w/ Dr. Nic, some of my co-workers on Windows were trying to install the cf-console plugin. After installing CF, Go, and configuring GOPATH, the following appears to work: (from cmd)

> go get github.com/danhigham/cf-console
> cf install-plugin %GOPATH%\bin\cf-console.exe

However, "cf console" thereafter exits silently (returns 1) in console.
I'll post back here when I have a little more debug info for you to go on.

**Comment by hagemt** [comment]
Attempts to execute bin\cf-console.exe produces the following output:

> panic: runtime error: index out of range
> 
> goroutine 1 [running]:
> github.com/cloudfoundry/cli/plugin.Start(0x3423e8, 0xc082002ea8)
>         C:/Go/home/src/github.com/cloudfoundry/cli/plugin/plugin_shim.go:12 +0x2ae
> main.main()
>         C:/Go/home/src/github.com/danhigham/cf-console/console.go:49 +0x6d
> 
> goroutine 6 [runnable]:
> os/signal.loop()
>         c:/go/src/os/signal/signal_unix.go:19
> created by os/signal.init·1
>         c:/go/src/os/signal/signal_unix.go:27 +0x3

**Comment by hagemt** [comment]
Not sure this was ever intended to work on Windows, (or Cygwin) but @drnic and I might be curious.

**Comment by hagemt** [comment]
Forgot to mention: I'm (personally) in an environment (Cygwin) with a working SSH client, and I can provide whatever else might be required to figure out what's going on. (or, how I can help smooth things out for them on Windows) Thanks!

P.S. Looks like the referenced https://github.com/danhigham/cf-console/blob/master/console.go#L49 is:

> plugin.Start(&ConsolePlugin{})

**Comment by danhigham** [comment]
hey @hagemt, I got this working just fine in Cygwin (see the image). Are you running "cf console &lt;app name&gt;" or running the binary directly?
![screen shot 2015-01-21 at 11 11 18 am](https://cloud.githubusercontent.com/assets/3974/5842930/aada179c-a15d-11e4-865d-e7d123e8310a.png)
